import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

const passages = [
  {
    title: "Lecture: Urban Heat Islands",
    content: `Today I want to talk about a phenomenon called the urban heat island effect. Basically, cities tend to be significantly warmer than the surrounding rural areas, sometimes by as much as five to ten degrees Celsius. Why does this happen?

Well, the main reason is the materials we use to build cities. Concrete, asphalt, and dark rooftops absorb much more solar radiation than natural surfaces like grass or forest, and they release that heat slowly throughout the day and night. Rural areas, on the other hand, have more vegetation, which provides shade and releases moisture into the air through a process called evapotranspiration, which has a cooling effect.

Another factor is the shape of cities themselves. Tall buildings create what we call urban canyons, which trap heat and reduce airflow. Combine that with the heat generated by vehicles, air conditioning units, and industrial activity, and you get a significant temperature difference compared to nearby rural areas.

Now, this isn't just an inconvenience. Urban heat islands can have serious consequences for public health, especially during heat waves, when city residents face higher risks of heat-related illness. They also increase energy consumption, since more air conditioning is needed to keep buildings cool, which in turn generates more heat, creating a kind of feedback loop.

Cities around the world are experimenting with solutions. Some are painting rooftops white to reflect sunlight instead of absorbing it. Others are investing in green roofs, which are rooftops covered with vegetation, or expanding urban parks and tree cover. These strategies can meaningfully reduce local temperatures, though implementing them at scale remains a significant challenge.`,
    questions: [
      {
        content: "What is the main topic of this lecture?",
        correctAnswer: "Why cities are warmer than surrounding rural areas and what can be done about it.",
        options: [
          "Why cities are warmer than surrounding rural areas and what can be done about it.",
          "How to build taller buildings more efficiently.",
          "The history of air conditioning technology.",
          "Why rural areas are becoming warmer than cities.",
        ],
        topic: "Main Idea",
      },
      {
        content: "According to the lecture, what is one reason cities absorb more heat?",
        correctAnswer: "Materials like concrete and asphalt absorb more solar radiation than natural surfaces.",
        options: [
          "Materials like concrete and asphalt absorb more solar radiation than natural surfaces.",
          "Cities have more trees than rural areas.",
          "Rural areas have taller buildings.",
          "Cities receive more sunlight overall than rural areas.",
        ],
        topic: "Detail",
      },
      {
        content: "What does the speaker mean by 'urban canyons'?",
        correctAnswer: "Narrow spaces between tall buildings that trap heat and reduce airflow.",
        options: [
          "Narrow spaces between tall buildings that trap heat and reduce airflow.",
          "Natural canyons located near cities.",
          "Underground tunnels used for transportation.",
          "Wide open parks in the center of cities.",
        ],
        topic: "Detail",
      },
      {
        content: "Why does the speaker mention the 'feedback loop' involving air conditioning?",
        correctAnswer: "To explain how cooling buildings can actually make the heat island effect worse.",
        options: [
          "To explain how cooling buildings can actually make the heat island effect worse.",
          "To argue that air conditioning should be banned in cities.",
          "To show that air conditioning has no effect on temperature.",
          "To describe how air conditioners are manufactured.",
        ],
        topic: "Author's Purpose",
      },
      {
        content: "What can be inferred about painting rooftops white?",
        correctAnswer: "It is intended to reflect sunlight rather than absorb it.",
        options: [
          "It is intended to reflect sunlight rather than absorb it.",
          "It is the only effective solution to urban heat islands.",
          "It increases energy consumption in buildings.",
          "It is more expensive than adding green roofs.",
        ],
        topic: "Inference",
      },
    ],
  },
  {
    title: "Conversation: Meeting with an Academic Advisor",
    content: `Student: Hi, thanks for meeting with me. I wanted to talk about my course schedule for next semester.

Advisor: Of course. I see you're majoring in Biology. What's on your mind?

Student: Well, I was planning to take Organic Chemistry and Genetics at the same time, but a few upperclassmen told me that might be too much, especially since both have heavy lab components.

Advisor: That's a fair concern. Both of those courses are known for being demanding, and if you stack them together, you might find yourself spending most of your week in the lab, with less time for other coursework or, frankly, for sleep.

Student: Right, that's what I was worried about. Would it make more sense to spread them across two semesters?

Advisor: I think that could work well, especially if you're also planning to keep your part-time job at the library. One option is to take Genetics this semester and push Organic Chemistry to next semester, when you'll have a lighter overall course load.

Student: That makes sense. Would that delay my graduation timeline though? I was hoping to graduate in four years.

Advisor: Let's see... if you take Organic Chemistry next semester and follow it with the second part in the following term, you'd still be on track. The sequence just needs to be completed before your final year, so you have some flexibility here.

Student: Okay, that's a relief. Should I also consider taking a summer course to stay ahead?

Advisor: It's an option, but not necessary based on your current progress. I'd only recommend it if you want to lighten a future semester or if you're considering a minor.

Student: I'll think about it. Thanks, this really helps clarify things.

Advisor: No problem. Feel free to schedule another appointment if you want to finalize your plan closer to registration.`,
    questions: [
      {
        content: "Why does the student meet with the advisor?",
        correctAnswer: "To discuss whether to take two demanding courses at the same time.",
        options: [
          "To discuss whether to take two demanding courses at the same time.",
          "To change her major from Biology to Chemistry.",
          "To apply for a part-time job at the library.",
          "To request an extension on a lab assignment.",
        ],
        topic: "Main Idea",
      },
      {
        content: "What does the advisor suggest the student do?",
        correctAnswer: "Take Genetics this semester and Organic Chemistry next semester.",
        options: [
          "Take Genetics this semester and Organic Chemistry next semester.",
          "Drop both courses entirely.",
          "Take both courses in summer school instead.",
          "Switch to a different major.",
        ],
        topic: "Detail",
      },
      {
        content: "Why was the student concerned about taking both courses together?",
        correctAnswer: "Both courses have heavy lab components and could take up most of her time.",
        options: [
          "Both courses have heavy lab components and could take up most of her time.",
          "She does not enjoy science courses.",
          "The courses are only offered at the same time slot.",
          "She is not eligible to take Organic Chemistry yet.",
        ],
        topic: "Detail",
      },
      {
        content: "What can be inferred about the student's job at the library?",
        correctAnswer: "It is a factor the advisor considers when planning her course load.",
        options: [
          "It is a factor the advisor considers when planning her course load.",
          "It is unrelated to her academic schedule.",
          "The advisor recommends she quit the job immediately.",
          "It is a requirement for her Biology major.",
        ],
        topic: "Inference",
      },
      {
        content: "Why does the advisor mention a summer course near the end of the conversation?",
        correctAnswer: "As an optional suggestion, not a necessary step for the student.",
        options: [
          "As an optional suggestion, not a necessary step for the student.",
          "As a mandatory requirement for graduation.",
          "To warn the student she is behind schedule.",
          "To explain a new university policy.",
        ],
        topic: "Author's Purpose",
      },
    ],
  },
];

async function main() {
  for (const p of passages) {
    await prisma.readingPassage.create({
      data: {
        module: "toefl",
        mode: "listening",
        level: "toefl",
        title: p.title,
        content: p.content,
        questions: {
          create: p.questions.map((q) => ({
            module: "toefl",
            section: "listening",
            topic: q.topic,
            level: "toefl",
            difficulty: 3,
            type: "MCQ",
            content: q.content,
            correctAnswer: q.correctAnswer,
            options: {
              create: q.options.map((opt) => ({
                content: opt,
                isCorrect: opt === q.correctAnswer,
              })),
            },
          })),
        },
      },
    });
  }

  console.log(`Seeded ${passages.length} TOEFL listening passages with questions.`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });